include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # --- CONST ENFORCEMENT ---
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # --- CODE QUALITY / CLEAN ARCH STYLE ---
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    constant_identifier_names: false
    directives_ordering: true
    omit_local_variable_types: false
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    unawaited_futures: true
    use_super_parameters: true
