/// Generated file placeholder for injectable code generation
/// 
/// WHY: This file will be auto-generated by the injectable package when using
/// @injectable, @singleton, and @module annotations.
/// 
/// HOW TO GENERATE: Run the following command:
/// ```bash
/// flutter pub run build_runner build --delete-conflicting-outputs
/// ```
/// 
/// NOTE: For now, we're using manual registration in injector.dart.
/// When the project grows, you can migrate to injectable annotations for
/// automatic dependency registration.
/// 
/// EXAMPLE USAGE WITH INJECTABLE:
/// ```dart
/// @injectable
/// class MyRepository {
///   final ApiService apiService;
///   MyRepository(this.apiService);
/// }
/// ```

// This file will be generated by build_runner
// For now, dependencies are registered manually in injector.dart
